source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'YBAlertController_Example', :exclusive => true do
  pod "YBAlertController", :path => "../"
end

target 'YBAlertController_Tests', :exclusive => true do
  pod "YBAlertController", :path => "../"
end
